/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoibm_GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author baxx
 */
public class VentanaCrono extends javax.swing.JFrame {
   private Timer tiempo;
    private  boolean estado = false; //true cuando esta corriendo false cuando esta detenido o en 0
    private  int h = 00,m = 00, s =00,ms=00;
    
    
    ActionListener l = new ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
           ms++;
           
           if(ms==100){
              
               s++;
               ms=00;
           }
           if(s==60){
               m++;
               s=00;
           }
           
            if(m==60){
               h++;
               m=00;
           }
          etiquetaTiempo.setText(fortmatoHora(h)+"h : "+fortmatoHora(m)+"m : "+fortmatoHora(s)+"s: "+fortmatoHora(ms)+"ms");
           
       }
    };
    
    public VentanaCrono() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        btnIDetener.setEnabled(false);
        btnPausa.setEnabled(false);
        tiempo= new Timer(10, l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        btnPausa = new javax.swing.JButton();
        btnIDetener = new javax.swing.JButton();
        btnIniciar1 = new javax.swing.JButton();
        imagenCrono = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setMaximumSize(new java.awt.Dimension(513, 300));
        panel1.setMinimumSize(new java.awt.Dimension(513, 300));
        panel1.setPreferredSize(new java.awt.Dimension(513, 300));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaCronometro.setFont(new java.awt.Font("JetBrains Mono Medium", 1, 48)); // NOI18N
        etiquetaCronometro.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCronometro.setText("Cronometro");
        panel1.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        etiquetaTiempo.setBackground(new java.awt.Color(153, 255, 255));
        etiquetaTiempo.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(51, 51, 51));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00h : 00m : 00s: 00ms");
        etiquetaTiempo.setOpaque(true);
        panel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 340, -1));

        btnPausa.setText("Pausar");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        panel1.add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 120, 40));

        btnIDetener.setText("Detener");
        btnIDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDetenerActionPerformed(evt);
            }
        });
        panel1.add(btnIDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 40));

        btnIniciar1.setText("Iniciar");
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });
        panel1.add(btnIniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 40));

        imagenCrono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crono.png"))); // NOI18N
        panel1.add(imagenCrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, 150));

        imagenFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\Documents\\NetBeansProjects\\cursoIBM\\src\\imagenes\\fondo.jpg")); // NOI18N
        panel1.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDetenerActionPerformed
        tiempo.stop();
        h=0;
        m=0;
        s=0;
        ms=0;
        etiquetaTiempo.setText(fortmatoHora(h)+"h : "+fortmatoHora(m)+"m : "+fortmatoHora(s)+"s: "+fortmatoHora(ms)+"ms");
        btnIniciar1.setText("Iniciar");
        btnIniciar1.setEnabled(true);
        btnIDetener.setEnabled(false);
        btnPausa.setEnabled(false);
    }//GEN-LAST:event_btnIDetenerActionPerformed

    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        tiempo.start();
        btnIniciar1.setText("Reanudar");
        btnIniciar1.setEnabled(false);
        btnIDetener.setEnabled(true);
        btnPausa.setEnabled(true);
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        tiempo.stop();
         btnIniciar1.setEnabled(true);
         btnPausa.setEnabled(false);
        
    }//GEN-LAST:event_btnPausaActionPerformed

    
    public String fortmatoHora(int n){
        String numFormart="";
        if(n<10){
           return numFormart="0"+n;
        }else{
            return numFormart+=n;
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIDetener;
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnPausa;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel imagenCrono;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
