/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoibm_GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author baxx
 */
public class VentanaLogin extends javax.swing.JFrame {

    final String pass = "macaron123", username= "baxx11";
    int intentos =3;
    
    
    public VentanaLogin() {
        initComponents();
        
        this.setLocationRelativeTo(null);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        usuerTxt1 = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        etiquetaImgUser = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 700));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 100, 40));

        passwordLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        passwordLabel.setText("Contraseña");
        panel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        etiquetaNombre.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        etiquetaNombre.setText("Nombre de usuario");
        panel1.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));
        panel1.add(usuerTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 350, 40));
        panel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 350, 40));

        etiquetaImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuer.png"))); // NOI18N
        panel1.add(etiquetaImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 160, 140));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 130, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo (2).jpg"))); // NOI18N
        panel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        if(intentos >0){
            System.out.println(intentos);
            String ususarioIngresado = usuerTxt1.getText();
            String contraseñaIngresada = "";
            
            for (int i = 0; i < passwordTxt.getPassword().length; i++) {
                contraseñaIngresada += passwordTxt.getPassword()[i];
            
            }
            
            
                if(validacion(ususarioIngresado, contraseñaIngresada)){
                JOptionPane.showMessageDialog(null, "Has ingresado al sistema");
                
                }else {
                    System.out.println("entron"+ intentos);
                        intentos--;


                }
                
            }else{
                if (intentos ==0){
                            
                        JOptionPane.showMessageDialog(null, "ha excedido el limite de intentos, por favor intente mas tarde");
                            btnIngresar.setEnabled(false);
                        }
            }

            
            
            
        
            
    }//GEN-LAST:event_btnIngresarActionPerformed
    
    
    public boolean validacion(String user, String passwword){
        
        boolean accessSuccesfuly = false;
        
        if(user.equals(username)&& passwword.equalsIgnoreCase(pass)){
        
                accessSuccesfuly= true;
        
        }
        
        if(!user.equals(username) && (!passwword.equals(pass))){
            JOptionPane.showMessageDialog(null, "Error los datos ingresados no conincden con ningun usuario");
        }else{
            if (!user.equals(username)) {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado, por favor intente de nuevo");
            }
            if(!passwword.equals(pass)){
                JOptionPane.showMessageDialog(null, "La contraseña no coincide con el usuario, por favor intente de nuevo");
            }
        }
        
        
        
        return accessSuccesfuly;
               
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel etiquetaImgUser;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usuerTxt1;
    // End of variables declaration//GEN-END:variables
}
