/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoIbm_DB.dbimg;

import com.mysql.jdbc.Buffer;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author baxx
 */
public class VentanaImagen extends javax.swing.JFrame {

    Imagen imganePanelActual;
    private static final String url="jdbc:mysql://localhost:3306/images?autoReconnet=true&useSSL=false";
    private static final String user="root";
    private static final String password ="1234";
    PreparedStatement ps;
    ResultSet rs;
    
    public VentanaImagen() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImg = new javax.swing.JPanel();
        btn_charge = new javax.swing.JButton();
        btn_viewimg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        btn_charge.setText("Cargar");
        btn_charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chargeActionPerformed(evt);
            }
        });

        btn_viewimg.setText("mostrar");
        btn_viewimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewimgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btn_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244)
                .addComponent(btn_viewimg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_viewimg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chargeActionPerformed
        Connection conn = getConnection();
        
        JFileChooser chooserImg = new JFileChooser();
        chooserImg.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filterex = new FileNameExtensionFilter(".png", "png");
        FileNameExtensionFilter filterex2 = new FileNameExtensionFilter(".jpg", "jpg");
        chooserImg.setFileFilter(filterex);
        chooserImg.setFileFilter(filterex2);
        int selection = chooserImg.showOpenDialog(this);
        
        
        
        if(selection== JFileChooser.APPROVE_OPTION){
            FileInputStream fis = null;
            try {
                File archivoimg = chooserImg.getSelectedFile();
                fis = new FileInputStream(archivoimg);
                
                ps = (PreparedStatement) conn.prepareStatement("insert into imagenes(imagen) values(?)");
                ps.setBlob(1, fis);
//                ps.setBinaryStream(1, fis, (int)archivoimg.length());
                int exQuery=ps.executeUpdate();
                if(exQuery>0){
                    JOptionPane.showMessageDialog(null, "La imagen fue guardada con exito");
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaImagen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaImagen.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fis.close();
                } catch (IOException ex) {
                    Logger.getLogger(VentanaImagen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        
        
        
        
       
        
    }//GEN-LAST:event_btn_chargeActionPerformed

    private void btn_viewimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewimgActionPerformed
        Connection conn = getConnection();
        int idimg = Integer.parseInt(JOptionPane.showInputDialog("ingrese el id de la imagen que desea mostrar"));
        
        if(imganePanelActual!=null){
                panelImg.remove(imganePanelActual);
                panelImg.repaint();
            }
        
        try {
            ps = (PreparedStatement) conn.prepareStatement("select imagen from imagenes where idimagenes=?");
            ps.setInt(1, idimg);
            rs=ps.executeQuery();
            
            
            BufferedImage bfi = null;
            
            if(rs.next()){
                InputStream img= rs.getBinaryStream("imagen");
                bfi = ImageIO.read(img);
                
                int ancho = panelImg.getWidth();
                int alto = panelImg.getHeight();
                imganePanelActual = new Imagen(ancho, alto, bfi);
                panelImg.add(imganePanelActual);
                panelImg.repaint();
            }
        } catch (Exception e) {
            System.err.println("ERROR: " +e);
        }
      
            
    }//GEN-LAST:event_btn_viewimgActionPerformed
    
    private Connection getConnection(){
        Connection connection=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=(Connection) DriverManager.getConnection(url,user,password);
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
        return connection;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaImagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_charge;
    private javax.swing.JButton btn_viewimg;
    private javax.swing.JPanel panelImg;
    // End of variables declaration//GEN-END:variables
}
