/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoIbm_DB;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Date;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

public class VentanaPruebaDB extends javax.swing.JFrame {

    private static final String url ="jdbc:mysql://localhost:3306/school?autoReconnet=true&useSSL=false";
    private static final String user="root";
    private static final String password = "1234";
    PreparedStatement ps;
    ResultSet rs ;
        
    /**
     * Creates new form VentanaPruebaDB
     */
    public VentanaPruebaDB() {
        initComponents();
        setLocationRelativeTo(null);
        id_input.disable();
       
        update_btn.setVisible(false);
        delete_btn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insert_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_student_label = new javax.swing.JLabel();
        name_Studen_input = new javax.swing.JTextField();
        lastname_student_label = new javax.swing.JLabel();
        lastname_Studen_input = new javax.swing.JTextField();
        date_birth_label = new javax.swing.JLabel();
        day_input = new javax.swing.JTextField();
        age_student_input = new javax.swing.JTextField();
        year_input = new javax.swing.JTextField();
        month_input = new javax.swing.JTextField();
        name_student_label3 = new javax.swing.JLabel();
        date_birth_label1 = new javax.swing.JLabel();
        date_birth_label2 = new javax.swing.JLabel();
        date_birth_label3 = new javax.swing.JLabel();
        id_input = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        search_input = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert_btn.setBackground(new java.awt.Color(0, 255, 102));
        insert_btn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        insert_btn.setForeground(new java.awt.Color(51, 51, 51));
        insert_btn.setText("Registrar");
        insert_btn.setOpaque(false);
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        jPanel1.add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 100, 50));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Internet-para-estudiantes-destacada.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, 265, 268));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de Registro");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 46, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        name_student_label.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        name_student_label.setForeground(new java.awt.Color(51, 51, 51));
        name_student_label.setText("Nombre del Estudiante");
        jPanel1.add(name_student_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 150, -1));

        name_Studen_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_Studen_inputActionPerformed(evt);
            }
        });
        jPanel1.add(name_Studen_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 270, 40));

        lastname_student_label.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lastname_student_label.setForeground(new java.awt.Color(51, 51, 51));
        lastname_student_label.setText("Apellido del Estudiante");
        jPanel1.add(lastname_student_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 150, -1));

        lastname_Studen_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname_Studen_inputActionPerformed(evt);
            }
        });
        jPanel1.add(lastname_Studen_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 270, 40));

        date_birth_label.setFont(new java.awt.Font("Dubai", 0, 10)); // NOI18N
        date_birth_label.setForeground(new java.awt.Color(51, 51, 51));
        date_birth_label.setText("Dia");
        jPanel1.add(date_birth_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 30, -1));

        day_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_inputActionPerformed(evt);
            }
        });
        jPanel1.add(day_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 60, 40));

        age_student_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_student_inputActionPerformed(evt);
            }
        });
        jPanel1.add(age_student_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 270, 40));

        year_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_inputActionPerformed(evt);
            }
        });
        jPanel1.add(year_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 130, 40));

        month_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_inputActionPerformed(evt);
            }
        });
        jPanel1.add(month_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 60, 40));

        name_student_label3.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        name_student_label3.setForeground(new java.awt.Color(51, 51, 51));
        name_student_label3.setText("Edad");
        jPanel1.add(name_student_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, -1));

        date_birth_label1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        date_birth_label1.setForeground(new java.awt.Color(51, 51, 51));
        date_birth_label1.setText("Fecha de nacimiento");
        jPanel1.add(date_birth_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 150, -1));

        date_birth_label2.setFont(new java.awt.Font("Dubai", 0, 10)); // NOI18N
        date_birth_label2.setForeground(new java.awt.Color(51, 51, 51));
        date_birth_label2.setText("Año");
        jPanel1.add(date_birth_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 30, -1));

        date_birth_label3.setFont(new java.awt.Font("Dubai", 0, 10)); // NOI18N
        date_birth_label3.setForeground(new java.awt.Color(51, 51, 51));
        date_birth_label3.setText("Mes");
        jPanel1.add(date_birth_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 30, -1));

        id_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_input.setText("00000");
        jPanel1.add(id_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 50, -1));

        search_btn.setText("Buscar");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 320, 70));

        clear_btn.setBackground(new java.awt.Color(204, 255, 255));
        clear_btn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(51, 51, 51));
        clear_btn.setText("Limpiar");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 80, 40));

        delete_btn.setBackground(new java.awt.Color(255, 102, 102));
        delete_btn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(51, 51, 51));
        delete_btn.setText("Borrar");
        delete_btn.setOpaque(false);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 70, 40));

        update_btn.setBackground(new java.awt.Color(255, 255, 102));
        update_btn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(51, 51, 51));
        update_btn.setText("Guardar");
        update_btn.setOpaque(false);
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 90, 40));

        jLabel3.setText("ID Estudiante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
       Connection conect= getConnection();
       String nameStudent = name_Studen_input.getText();
       String lastnameStudent = lastname_Studen_input.getText();
       String age = age_student_input.getText();
       String dateBirth = year_input.getText()+"-"+month_input.getText()+"-"+day_input.getText();
       
        try {
            ps= (PreparedStatement) conect.prepareStatement("insert into student(name,lastname,age,date_of_birth) values(?,?,?,?)");
            ps.setString(1, nameStudent);
            ps.setString(2, lastnameStudent);
            ps.setInt(3, Integer.parseInt(age));
            ps.setDate(4, Date.valueOf(dateBirth));
            
            int statementQuery= ps.executeUpdate();
            
            if(statementQuery>0){
                JOptionPane.showMessageDialog(null, "registro exitoso");
            }else{
                JOptionPane.showMessageDialog(null, "algo ha salido mal");
            }
            
            conect.close();
            
            clearFields();
        } catch (Exception e) {
            System.err.println("Erro: "+e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void name_Studen_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_Studen_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_Studen_inputActionPerformed

    private void lastname_Studen_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname_Studen_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastname_Studen_inputActionPerformed

    private void day_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day_inputActionPerformed

    private void age_student_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_student_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_student_inputActionPerformed

    private void year_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_inputActionPerformed

    private void month_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_inputActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        Connection conect= getConnection();
        
        
        int idStudent=Integer.parseInt(search_input.getText());
        insert_btn.setVisible(false);
        delete_btn.setVisible(true);
        update_btn.setVisible(true);
    
        
        
        try {
            if(idStudent>=0 ){
                
                ps = (PreparedStatement) conect.prepareStatement("select * from student where idstudent=?");
                ps.setInt(1, idStudent);
                rs=ps.executeQuery();
                if (rs.next()) {  
                    System.out.println("nombre: "+rs.getString("name")+ " Apellido: "+rs.getString("lastname")+" Edad: "+rs.getString("age")+ " fecha de nacimitento: "+ rs.getDate("date_of_birth"));
                
                    name_Studen_input.setText(rs.getString("name"));
                    lastname_Studen_input.setText(rs.getString("lastname"));
                    age_student_input.setText(rs.getString("age"));
                     SimpleDateFormat getYearFormat = new SimpleDateFormat("yyyy");
                    String currentYear = getYearFormat.format(rs.getDate("date_of_birth"));
                    year_input.setText(String.valueOf( currentYear ));
                    month_input.setText(String.valueOf( rs.getDate("date_of_birth").getMonth()));
                    day_input.setText(String.valueOf( rs.getDate("date_of_birth").getDay()));
                    id_input.setText(String.valueOf( rs.getInt("idstudent")));
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro Estudiante con ese codigo");
                    clearFields();
                }
            }else {
                
                 JOptionPane.showMessageDialog(null, "debe ingresar un codigo valido,");
                 clearFields();
            
            }
            
           
            
            
        } catch (Exception e) {
            System.err.println("Error: "+e);
        }
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        clearFields();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        Connection conect= getConnection();
       
        try {
            ps= (PreparedStatement) conect.prepareStatement("delete from student where idstudent=?");
            ps.setInt(1, Integer.parseInt(id_input.getText()));
            
            int statementQuery= ps.executeUpdate();
            
            if(statementQuery>0){
                JOptionPane.showMessageDialog(null, "Se a eliminado el usuario con exitoso");
                clearFields();
            }else{
                JOptionPane.showMessageDialog(null, "algo ha salido mal");
            }
            
            conect.close();
            
            
        } catch (Exception e) {
            System.err.println("Erro: "+e);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        Connection conect= getConnection();
        String nameStudent = name_Studen_input.getText();
        String lastnameStudent = lastname_Studen_input.getText();
        String age = age_student_input.getText();
        String dateBirth = year_input.getText()+"-"+month_input.getText()+"-"+day_input.getText();
        
        try {
            ps= (PreparedStatement) conect.prepareStatement("update student  set name=?,lastname=?,age=?,date_of_birth=? where idstudent=?");
            ps.setString(1, nameStudent);
            ps.setString(2, lastnameStudent);
            ps.setInt(3, Integer.parseInt(age));
            ps.setDate(4, Date.valueOf(dateBirth));
            ps.setInt(5, Integer.parseInt(id_input.getText()));
            
            int statementQuery= ps.executeUpdate();
            
            if(statementQuery>0){
                JOptionPane.showMessageDialog(null, "Los datos del estudiante se ha actualizado con exito");
                clearFields();
            }else{
                JOptionPane.showMessageDialog(null, "algo ha salido mal");
            }
            
            conect.close();
            
            
        } catch (Exception e) {
            System.err.println("Erro: "+e);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    public void clearFields(){
        name_Studen_input.setText("");
        lastname_Studen_input.setText("");
        age_student_input.setText("");
        year_input.setText("");
        month_input.setText("");
        day_input.setText("");
        id_input.setText("0000");
        search_input.setText("");
        update_btn.setVisible(false);
        delete_btn.setVisible(false);
        insert_btn.setVisible(true);
        
    }
    public Connection getConnection(){
        Connection connect = null;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect=(Connection) DriverManager.getConnection(url,user,password);
            
            
            
        } catch (Exception e) {
            System.err.println("ERROR: "+e);
        }
                
        return connect;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPruebaDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_student_input;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel date_birth_label;
    private javax.swing.JLabel date_birth_label1;
    private javax.swing.JLabel date_birth_label2;
    private javax.swing.JLabel date_birth_label3;
    private javax.swing.JTextField day_input;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField id_input;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastname_Studen_input;
    private javax.swing.JLabel lastname_student_label;
    private javax.swing.JTextField month_input;
    private javax.swing.JTextField name_Studen_input;
    private javax.swing.JLabel name_student_label;
    private javax.swing.JLabel name_student_label3;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_input;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField year_input;
    // End of variables declaration//GEN-END:variables
}
